//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviews
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantInfo", Namespace="http://schemas.datacontract.org/2004/07/Lab6")]
    public partial class RestaurantInfo : object
    {
        
        private int CostField;
        
        private string FoodTypeField;
        
        private int IdField;
        
        private RestaurantReviews.Address LocationField;
        
        private string NameField;
        
        private int RatingField;
        
        private string SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost
        {
            get
            {
                return this.CostField;
            }
            set
            {
                this.CostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodType
        {
            get
            {
                return this.FoodTypeField;
            }
            set
            {
                this.FoodTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantReviews.Address Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Lab6")]
    public partial class Address : object
    {
        
        private string CityField;
        
        private string PostalCodeField;
        
        private string ProvinceField;
        
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantReviews.IRestaurantReviewService")]
    public interface IRestaurantReviewService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantNamesResponse")]
        System.Collections.Generic.List<string> GetRestaurantNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantNamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetRestaurantNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetAllRestaurants", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetAllRestaurantsResponse")]
        System.Collections.Generic.List<RestaurantReviews.RestaurantInfo> GetAllRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetAllRestaurants", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetAllRestaurantsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RestaurantReviews.RestaurantInfo>> GetAllRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantById", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByIdResponse")]
        RestaurantReviews.RestaurantInfo GetRestaurantById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/GetRestaurantById", ReplyAction="http://tempuri.org/IRestaurantReviewService/GetRestaurantByIdResponse")]
        System.Threading.Tasks.Task<RestaurantReviews.RestaurantInfo> GetRestaurantByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IRestaurantReviewService/SaveRestaurantResponse")]
        void SaveRestaurant(RestaurantReviews.RestaurantInfo restInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IRestaurantReviewService/SaveRestaurantResponse")]
        System.Threading.Tasks.Task SaveRestaurantAsync(RestaurantReviews.RestaurantInfo restInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IRestaurantReviewServiceChannel : RestaurantReviews.IRestaurantReviewService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RestaurantReviewServiceClient : System.ServiceModel.ClientBase<RestaurantReviews.IRestaurantReviewService>, RestaurantReviews.IRestaurantReviewService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RestaurantReviewServiceClient() : 
                base(RestaurantReviewServiceClient.GetDefaultBinding(), RestaurantReviewServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), RestaurantReviewServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RestaurantReviewServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RestaurantReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<string> GetRestaurantNames()
        {
            return base.Channel.GetRestaurantNames();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetRestaurantNamesAsync()
        {
            return base.Channel.GetRestaurantNamesAsync();
        }
        
        public System.Collections.Generic.List<RestaurantReviews.RestaurantInfo> GetAllRestaurants()
        {
            return base.Channel.GetAllRestaurants();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RestaurantReviews.RestaurantInfo>> GetAllRestaurantsAsync()
        {
            return base.Channel.GetAllRestaurantsAsync();
        }
        
        public RestaurantReviews.RestaurantInfo GetRestaurantById(int id)
        {
            return base.Channel.GetRestaurantById(id);
        }
        
        public System.Threading.Tasks.Task<RestaurantReviews.RestaurantInfo> GetRestaurantByIdAsync(int id)
        {
            return base.Channel.GetRestaurantByIdAsync(id);
        }
        
        public void SaveRestaurant(RestaurantReviews.RestaurantInfo restInfo)
        {
            base.Channel.SaveRestaurant(restInfo);
        }
        
        public System.Threading.Tasks.Task SaveRestaurantAsync(RestaurantReviews.RestaurantInfo restInfo)
        {
            return base.Channel.SaveRestaurantAsync(restInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/OnlineService/RestaurantReviewService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RestaurantReviewServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RestaurantReviewServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRestaurantReviewService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRestaurantReviewService,
        }
    }
}
