<?php
	$bookList = array('PHP and MySQL Web Development (4th Edition)' => 49.95,
			  'Learning PHP, MySQL, and JavaScript' => 37.33,
			  'Beginning PHP and MySQL: From Novice to Professional' => 23.56,
			  'Head First PHP & MySQL' => 64.35,
			  'MySQL and PHP For Dummies, 4th Edition' => 49.44,
			  'Effortless E-Commerce with PHP and MySQL' => 26.56,
			  'PHP for the World Wide Web, Third Edition' => 113.34,
			  'The PHP Solutions: Dynamic Web Design Made Easy, Second Edition' => 120.35,
			  'Sams Teach Yourself PHP, MySQL and Apache All in One ' => 19.34,
			  'Essential Guide to Dreamweaver CS4 with CSS, Ajax, and PHP' => 75.95,
			  'Learning PHP 5' => 55.63,
			  'Advanced PHP Programming' => 90.11,
			  'You Want to Do What with PHP?' => 63.36,
			  'Web Database Applications with PHP & MySQL' => 25.29,
			  'Real-World Solutions for Developing PHP Frameworks and Applications' => 96.34,
			  'Core Web Application Development with PHP and MySQL' => 34.69,
			  'Securing PHP Web Applications' => 72.14,
                          'Murach\'s ASP.NET 4.6 Web Programming with C# 2015' => 55.5,
                          'Beginning ASP.NET 4.5.1: in C# and VB (Wrox Programmer to Programmer)' => 77.9,
                          'Pro ASP.NET Core MVC' => 75.95,
			  'Building Web Applications with Visual Studio 2017' => 55.63,
			  'ASP.NET Core 1.1 For Beginners: How To Build a MVC Website' => 90.11,
			  'ASP.NET Core Application Development: Building an application in four sprints' => 63.36,
			  'Beginning ASP.NET for Visual Studio 2015' => 25.29,
			  'Professional ASP.NET MVC 5' => 96.34,
			  'Pro ASP.NET Core MVC 2' => 34.69,
			  'Beginning ASP.NET 4.5 in C# (Experts Voice in .Net)' => 72.14,
                          'ASP.NET MVC 5 with Bootstrap and Knockout.js: Building Dynamic, Responsive Web Applications' => 55.5,
                          'ASP.NET For Beginners: The Simple Guide to Learning ASP.NET Web Programming Fast!' => 77.9,            
			  'Foundation PHP 5 for Flash' => 87.45
			);
        $_SESSION['bookList']=$bookList;
?>